import { Category } from '@/data/enums/category';
import { Unit } from '@/data/enums/unit';

export interface IngredientTemplate {
  id: string;
  krLabel: string;
  enLabel: string;
  emoji: string;
  category: Category; // categories의 category 값 사용 예정
  defaultUnit: Unit; // units의 unit 값 사용 예정
}

export const ingredientTemplates: IngredientTemplate[] = [
  // Vegetables
  {
    id: 'carrot',
    krLabel: '당근',
    enLabel: 'Carrot',
    emoji: '🥕',
    category: Category.VEGETABLE,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'onion',
    krLabel: '양파',
    enLabel: 'Onion',
    emoji: '🧅',
    category: Category.VEGETABLE,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'potato',
    krLabel: '감자',
    enLabel: 'Potato',
    emoji: '🥔',
    category: Category.VEGETABLE,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'cherry_tomatoes',
    krLabel: '방울토마토',
    enLabel: 'Cherry Tomatoes',
    emoji: '🍅',
    category: Category.VEGETABLE,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'tomato',
    krLabel: '토마토',
    enLabel: 'Tomato',
    emoji: '🍅',
    category: Category.VEGETABLE,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'lettuce',
    krLabel: '상추',
    enLabel: 'Lettuce',
    emoji: '🥬',
    category: Category.VEGETABLE,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'napa_cabbage',
    krLabel: '배추',
    enLabel: 'Napa Cabbage',
    emoji: '🥬',
    category: Category.VEGETABLE,
    defaultUnit: Unit.HEAD,
  },
  {
    id: 'broccoli',
    krLabel: '브로콜리',
    enLabel: 'Broccoli',
    emoji: '🥦',
    category: Category.VEGETABLE,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'cucumber',
    krLabel: '오이',
    enLabel: 'Cucumber',
    emoji: '🥒',
    category: Category.VEGETABLE,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'eggplant',
    krLabel: '가지',
    enLabel: 'Eggplant',
    emoji: '🍆',
    category: Category.VEGETABLE,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'bell_pepper',
    krLabel: '피망',
    enLabel: 'Bell Pepper',
    emoji: '🫑',
    category: Category.VEGETABLE,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'corn',
    krLabel: '옥수수',
    enLabel: 'Corn',
    emoji: '🌽',
    category: Category.VEGETABLE,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'mushroom',
    krLabel: '버섯',
    enLabel: 'Mushroom',
    emoji: '🍄',
    category: Category.VEGETABLE,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'shiitake_mushroom',
    krLabel: '표고버섯',
    enLabel: 'Shiitake Mushroom',
    emoji: '🍄',
    category: Category.VEGETABLE,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'oyster_mushroom',
    krLabel: '느타리버섯',
    enLabel: 'Oyster Mushroom',
    emoji: '🍄',
    category: Category.VEGETABLE,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'enoki_mushroom',
    krLabel: '팽이버섯',
    enLabel: 'Enoki Mushroom',
    emoji: '🍄',
    category: Category.VEGETABLE,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'king_oyster_mushroom',
    krLabel: '새송이버섯',
    enLabel: 'King Oyster Mushroom',
    emoji: '🍄',
    category: Category.VEGETABLE,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'button_mushroom',
    krLabel: '양송이버섯',
    enLabel: 'Button Mushroom',
    emoji: '🍄',
    category: Category.VEGETABLE,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'green_onion',
    krLabel: '대파',
    enLabel: 'Green Onion',
    emoji: '🧅',
    category: Category.VEGETABLE,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'chives',
    krLabel: '쪽파',
    enLabel: 'Chives',
    emoji: '🧅',
    category: Category.VEGETABLE,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'garlic',
    krLabel: '마늘',
    enLabel: 'Garlic',
    emoji: '🧄',
    category: Category.VEGETABLE,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'ginger',
    krLabel: '생강',
    enLabel: 'Ginger',
    emoji: '🫚',
    category: Category.VEGETABLE,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'chili_pepper',
    krLabel: '고추',
    enLabel: 'Chili Pepper',
    emoji: '🌶️',
    category: Category.VEGETABLE,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'perilla_leaf',
    krLabel: '깻잎',
    enLabel: 'Perilla Leaf',
    emoji: '🍃',
    category: Category.VEGETABLE,
    defaultUnit: Unit.SHEET,
  },
  {
    id: 'spinach',
    krLabel: '시금치',
    enLabel: 'Spinach',
    emoji: '🥬',
    category: Category.VEGETABLE,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'radish',
    krLabel: '무',
    enLabel: 'Radish',
    emoji: '🥕',
    category: Category.VEGETABLE,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'young_radish',
    krLabel: '알타리무',
    enLabel: 'Young Radish',
    emoji: '🥕',
    category: Category.VEGETABLE,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'zucchini',
    krLabel: '애호박',
    enLabel: 'Zucchini',
    emoji: '🥒',
    category: Category.VEGETABLE,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'cheongyang_chili',
    krLabel: '청양고추',
    enLabel: 'Cheongyang Chili',
    emoji: '🌶️',
    category: Category.VEGETABLE,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'paprika',
    krLabel: '파프리카',
    enLabel: 'Paprika',
    emoji: '🫑',
    category: Category.VEGETABLE,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'bean_sprout',
    krLabel: '콩나물',
    enLabel: 'Bean Sprout',
    emoji: '🌱',
    category: Category.VEGETABLE,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'mung_bean_sprout',
    krLabel: '숙주',
    enLabel: 'Mung Bean Sprout',
    emoji: '🌱',
    category: Category.VEGETABLE,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'water_parsley',
    krLabel: '미나리',
    enLabel: 'Water Parsley',
    emoji: '🌿',
    category: Category.VEGETABLE,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'buchu',
    krLabel: '부추',
    enLabel: 'Buchu',
    emoji: '🌿',
    category: Category.VEGETABLE,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'crown_daisy',
    krLabel: '쑥갓',
    enLabel: 'Crown Daisy',
    emoji: '🌿',
    category: Category.VEGETABLE,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'kale',
    krLabel: '케일',
    enLabel: 'Kale',
    emoji: '🥬',
    category: Category.VEGETABLE,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'cabbage',
    krLabel: '양배추',
    enLabel: 'Cabbage',
    emoji: '🥬',
    category: Category.VEGETABLE,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'bok_choy',
    krLabel: '청경채',
    enLabel: 'Bok Choy',
    emoji: '🥬',
    category: Category.VEGETABLE,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'cauliflower',
    krLabel: '콜리플라워',
    enLabel: 'Cauliflower',
    emoji: '🥦',
    category: Category.VEGETABLE,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'asparagus',
    krLabel: '아스파라거스',
    enLabel: 'Asparagus',
    emoji: '🥒',
    category: Category.VEGETABLE,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'celery',
    krLabel: '셀러리',
    enLabel: 'Celery',
    emoji: '🥬',
    category: Category.VEGETABLE,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'lotus_root',
    krLabel: '연근',
    enLabel: 'Lotus Root',
    emoji: '🪷',
    category: Category.VEGETABLE,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'burdock',
    krLabel: '우엉',
    enLabel: 'Burdock',
    emoji: '🥕',
    category: Category.VEGETABLE,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'bellflower_root',
    krLabel: '도라지',
    enLabel: 'Bellflower Root',
    emoji: '🌿',
    category: Category.VEGETABLE,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'sweet_potato',
    krLabel: '고구마',
    enLabel: 'Sweet Potato',
    emoji: '🍠',
    category: Category.VEGETABLE,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'pumpkin',
    krLabel: '단호박',
    enLabel: 'Pumpkin',
    emoji: '🎃',
    category: Category.VEGETABLE,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'old_pumpkin',
    krLabel: '늙은호박',
    enLabel: 'Old Pumpkin',
    emoji: '🎃',
    category: Category.VEGETABLE,
    defaultUnit: Unit.PIECE,
  },

  // Fruits
  {
    id: 'apple',
    krLabel: '사과',
    enLabel: 'Apple',
    emoji: '🍎',
    category: Category.FRUIT,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'banana',
    krLabel: '바나나',
    enLabel: 'Banana',
    emoji: '🍌',
    category: Category.FRUIT,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'orange',
    krLabel: '오렌지',
    enLabel: 'Orange',
    emoji: '🍊',
    category: Category.FRUIT,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'strawberry',
    krLabel: '딸기',
    enLabel: 'Strawberry',
    emoji: '🍓',
    category: Category.FRUIT,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'grape',
    krLabel: '포도',
    enLabel: 'Grape',
    emoji: '🍇',
    category: Category.FRUIT,
    defaultUnit: Unit.CLUSTER,
  },
  {
    id: 'shine_muscat',
    krLabel: '샤인머스캣',
    enLabel: 'Shine Muscat',
    emoji: '🍇',
    category: Category.FRUIT,
    defaultUnit: Unit.CLUSTER,
  },
  {
    id: 'watermelon',
    krLabel: '수박',
    enLabel: 'Watermelon',
    emoji: '🍉',
    category: Category.FRUIT,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'peach',
    krLabel: '복숭아',
    enLabel: 'Peach',
    emoji: '🍑',
    category: Category.FRUIT,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'kiwi',
    krLabel: '키위',
    enLabel: 'Kiwi',
    emoji: '🥝',
    category: Category.FRUIT,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'mango',
    krLabel: '망고',
    enLabel: 'Mango',
    emoji: '🥭',
    category: Category.FRUIT,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'pineapple',
    krLabel: '파인애플',
    enLabel: 'Pineapple',
    emoji: '🍍',
    category: Category.FRUIT,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'lemon',
    krLabel: '레몬',
    enLabel: 'Lemon',
    emoji: '🍋',
    category: Category.FRUIT,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'lime',
    krLabel: '라임',
    enLabel: 'Lime',
    emoji: '🍋‍🟩',
    category: Category.FRUIT,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'cherry',
    krLabel: '체리',
    enLabel: 'Cherry',
    emoji: '🍒',
    category: Category.FRUIT,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'pear',
    krLabel: '배',
    enLabel: 'Pear',
    emoji: '🍐',
    category: Category.FRUIT,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'tangerine',
    krLabel: '귤',
    enLabel: 'Tangerine',
    emoji: '🍊',
    category: Category.FRUIT,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'hallabong',
    krLabel: '한라봉',
    enLabel: 'Hallabong',
    emoji: '🍊',
    category: Category.FRUIT,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'cheonhaehyang',
    krLabel: '천혜향',
    enLabel: 'Cheonhaehyang',
    emoji: '🍊',
    category: Category.FRUIT,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'plum',
    krLabel: '자두',
    enLabel: 'Plum',
    emoji: '🍑',
    category: Category.FRUIT,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'oriental_melon',
    krLabel: '참외',
    enLabel: 'Oriental Melon',
    emoji: '🍈',
    category: Category.FRUIT,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'melon',
    krLabel: '메론',
    enLabel: 'Melon',
    emoji: '🍈',
    category: Category.FRUIT,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'blueberry',
    krLabel: '블루베리',
    enLabel: 'Blueberry',
    emoji: '🫐',
    category: Category.FRUIT,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'avocado',
    krLabel: '아보카도',
    enLabel: 'Avocado',
    emoji: '🥑',
    category: Category.FRUIT,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'persimmon',
    krLabel: '감',
    enLabel: 'Persimmon',
    emoji: '🟠',
    category: Category.FRUIT,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'dried_persimmon',
    krLabel: '곶감',
    enLabel: 'Dried Persimmon',
    emoji: '🟠',
    category: Category.FRUIT,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'jujube',
    krLabel: '대추',
    enLabel: 'Jujube',
    emoji: '🫒',
    category: Category.FRUIT,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'grapefruit',
    krLabel: '자몽',
    enLabel: 'Grapefruit',
    emoji: '🍊',
    category: Category.FRUIT,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'dragon_fruit',
    krLabel: '용과',
    enLabel: 'Dragon Fruit',
    emoji: '🐉',
    category: Category.FRUIT,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'durian',
    krLabel: '두리안',
    enLabel: 'Durian',
    emoji: '🥥',
    category: Category.FRUIT,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'coconut',
    krLabel: '코코넛',
    enLabel: 'Coconut',
    emoji: '🥥',
    category: Category.FRUIT,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'passion_fruit',
    krLabel: '패션후르츠',
    enLabel: 'Passion Fruit',
    emoji: '🥝',
    category: Category.FRUIT,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'olive',
    krLabel: '올리브',
    enLabel: 'Olive',
    emoji: '🫒',
    category: Category.FRUIT,
    defaultUnit: Unit.GRAM,
  },

  // Meat
  {
    id: 'beef',
    krLabel: '소고기',
    enLabel: 'Beef',
    emoji: '🥩',
    category: Category.MEAT,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'pork',
    krLabel: '돼지고기',
    enLabel: 'Pork',
    emoji: '🥓',
    category: Category.MEAT,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'chicken',
    krLabel: '닭고기',
    enLabel: 'Chicken',
    emoji: '🍗',
    category: Category.MEAT,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'pork_belly',
    krLabel: '삼겹살',
    enLabel: 'Pork Belly',
    emoji: '🥓',
    category: Category.MEAT,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'pork_neck',
    krLabel: '목살',
    enLabel: 'Pork Neck',
    emoji: '🥩',
    category: Category.MEAT,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'tenderloin',
    krLabel: '안심',
    enLabel: 'Tenderloin',
    emoji: '🥩',
    category: Category.MEAT,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'sirloin',
    krLabel: '등심',
    enLabel: 'Sirloin',
    emoji: '🥩',
    category: Category.MEAT,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'striploin',
    krLabel: '채끝',
    enLabel: 'Striploin',
    emoji: '🥩',
    category: Category.MEAT,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'brisket',
    krLabel: '양지',
    enLabel: 'Brisket',
    emoji: '🥩',
    category: Category.MEAT,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'shank',
    krLabel: '사태',
    enLabel: 'Shank',
    emoji: '🥩',
    category: Category.MEAT,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'round',
    krLabel: '우둔',
    enLabel: 'Round',
    emoji: '🥩',
    category: Category.MEAT,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'ribs',
    krLabel: '갈비',
    enLabel: 'Ribs',
    emoji: '🥩',
    category: Category.MEAT,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'chicken_breast',
    krLabel: '닭가슴살',
    enLabel: 'Chicken Breast',
    emoji: '🍗',
    category: Category.MEAT,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'chicken_drumstick',
    krLabel: '닭다리',
    enLabel: 'Chicken Drumstick',
    emoji: '🍗',
    category: Category.MEAT,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'chicken_wing',
    krLabel: '닭날개',
    enLabel: 'Chicken Wing',
    emoji: '🍗',
    category: Category.MEAT,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'duck_meat',
    krLabel: '오리고기',
    enLabel: 'Duck Meat',
    emoji: '🦆',
    category: Category.MEAT,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'bacon',
    krLabel: '베이컨',
    enLabel: 'Bacon',
    emoji: '🥓',
    category: Category.MEAT,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'sausage',
    krLabel: '소시지',
    enLabel: 'Sausage',
    emoji: '🌭',
    category: Category.MEAT,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'ham',
    krLabel: '햄',
    enLabel: 'Ham',
    emoji: '🍖',
    category: Category.MEAT,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'spam',
    krLabel: '스팸',
    enLabel: 'Spam',
    emoji: '🥫',
    category: Category.MEAT,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'ground_beef',
    krLabel: '다진소고기',
    enLabel: 'Ground Beef',
    emoji: '🥩',
    category: Category.MEAT,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'ground_pork',
    krLabel: '다진돼지고기',
    enLabel: 'Ground Pork',
    emoji: '🥓',
    category: Category.MEAT,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'lamb',
    krLabel: '양고기',
    enLabel: 'Lamb',
    emoji: '🍖',
    category: Category.MEAT,
    defaultUnit: Unit.GRAM,
  },

  // Seafood
  {
    id: 'mackerel',
    krLabel: '고등어',
    enLabel: 'Mackerel',
    emoji: '🐟',
    category: Category.SEAFOOD,
    defaultUnit: Unit.WHOLE,
  },
  {
    id: 'salmon',
    krLabel: '연어',
    enLabel: 'Salmon',
    emoji: '🐟',
    category: Category.SEAFOOD,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'tuna',
    krLabel: '참치',
    enLabel: 'Tuna',
    emoji: '🐟',
    category: Category.SEAFOOD,
    defaultUnit: Unit.WHOLE,
  },
  {
    id: 'flatfish',
    krLabel: '광어',
    enLabel: 'Flatfish',
    emoji: '🐟',
    category: Category.SEAFOOD,
    defaultUnit: Unit.WHOLE,
  },
  {
    id: 'rockfish',
    krLabel: '우럭',
    enLabel: 'Rockfish',
    emoji: '🐟',
    category: Category.SEAFOOD,
    defaultUnit: Unit.WHOLE,
  },
  {
    id: 'sea_bream',
    krLabel: '도미',
    enLabel: 'Sea Bream',
    emoji: '🐟',
    category: Category.SEAFOOD,
    defaultUnit: Unit.WHOLE,
  },
  {
    id: 'squid',
    krLabel: '오징어',
    enLabel: 'Squid',
    emoji: '🦑',
    category: Category.SEAFOOD,
    defaultUnit: Unit.WHOLE,
  },
  {
    id: 'octopus',
    krLabel: '문어',
    enLabel: 'Octopus',
    emoji: '🐙',
    category: Category.SEAFOOD,
    defaultUnit: Unit.WHOLE,
  },
  {
    id: 'small_octopus',
    krLabel: '낙지',
    enLabel: 'Small Octopus',
    emoji: '🐙',
    category: Category.SEAFOOD,
    defaultUnit: Unit.WHOLE,
  },
  {
    id: 'webfoot_octopus',
    krLabel: '주꾸미',
    enLabel: 'Webfoot Octopus',
    emoji: '🐙',
    category: Category.SEAFOOD,
    defaultUnit: Unit.WHOLE,
  },
  {
    id: 'shrimp',
    krLabel: '새우',
    enLabel: 'Shrimp',
    emoji: '🦐',
    category: Category.SEAFOOD,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'prawn',
    krLabel: '대하',
    enLabel: 'Prawn',
    emoji: '🦐',
    category: Category.SEAFOOD,
    defaultUnit: Unit.WHOLE,
  },
  {
    id: 'croaker',
    krLabel: '조기',
    enLabel: 'Croaker',
    emoji: '🐟',
    category: Category.SEAFOOD,
    defaultUnit: Unit.WHOLE,
  },
  {
    id: 'cutlassfish',
    krLabel: '갈치',
    enLabel: 'Cutlassfish',
    emoji: '🐟',
    category: Category.SEAFOOD,
    defaultUnit: Unit.WHOLE,
  },
  {
    id: 'pacific_saury',
    krLabel: '꽁치',
    enLabel: 'Pacific Saury',
    emoji: '🐟',
    category: Category.SEAFOOD,
    defaultUnit: Unit.WHOLE,
  },
  {
    id: 'spanish_mackerel',
    krLabel: '삼치',
    enLabel: 'Spanish Mackerel',
    emoji: '🐟',
    category: Category.SEAFOOD,
    defaultUnit: Unit.WHOLE,
  },
  {
    id: 'yellowtail',
    krLabel: '방어',
    enLabel: 'Yellowtail',
    emoji: '🐟',
    category: Category.SEAFOOD,
    defaultUnit: Unit.WHOLE,
  },
  {
    id: 'anchovy',
    krLabel: '멸치',
    enLabel: 'Anchovy',
    emoji: '🐟',
    category: Category.SEAFOOD,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'broth_anchovy',
    krLabel: '국물멸치',
    enLabel: 'Broth Anchovy',
    emoji: '🐟',
    category: Category.SEAFOOD,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'fried_anchovy',
    krLabel: '볶음멸치',
    enLabel: 'Fried Anchovy',
    emoji: '🐟',
    category: Category.SEAFOOD,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'pollock',
    krLabel: '명태',
    enLabel: 'Pollock',
    emoji: '🐟',
    category: Category.SEAFOOD,
    defaultUnit: Unit.WHOLE,
  },
  {
    id: 'dried_pollock',
    krLabel: '북어',
    enLabel: 'Dried Pollock',
    emoji: '🐟',
    category: Category.SEAFOOD,
    defaultUnit: Unit.WHOLE,
  },
  {
    id: 'yellow_dried_pollock',
    krLabel: '황태',
    enLabel: 'Yellow Dried Pollock',
    emoji: '🐟',
    category: Category.SEAFOOD,
    defaultUnit: Unit.WHOLE,
  },
  {
    id: 'clam',
    krLabel: '조개',
    enLabel: 'Clam',
    emoji: '🦪',
    category: Category.SEAFOOD,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'short_neck_clam',
    krLabel: '바지락',
    enLabel: 'Short-Neck Clam',
    emoji: '🦪',
    category: Category.SEAFOOD,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'manila_clam',
    krLabel: '모시조개',
    enLabel: 'Manila Clam',
    emoji: '🦪',
    category: Category.SEAFOOD,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'pen_shell',
    krLabel: '키조개',
    enLabel: 'Pen Shell',
    emoji: '🦪',
    category: Category.SEAFOOD,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'scallop',
    krLabel: '가리비',
    enLabel: 'Scallop',
    emoji: '🦪',
    category: Category.SEAFOOD,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'mussel',
    krLabel: '홍합',
    enLabel: 'Mussel',
    emoji: '🦪',
    category: Category.SEAFOOD,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'abalone',
    krLabel: '전복',
    enLabel: 'Abalone',
    emoji: '🦪',
    category: Category.SEAFOOD,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'turban_shell',
    krLabel: '소라',
    enLabel: 'Turban Shell',
    emoji: '🐚',
    category: Category.SEAFOOD,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'whelk',
    krLabel: '골뱅이',
    enLabel: 'Whelk',
    emoji: '🐚',
    category: Category.SEAFOOD,
    defaultUnit: Unit.CAN,
  },
  {
    id: 'crab',
    krLabel: '게',
    enLabel: 'Crab',
    emoji: '🦀',
    category: Category.SEAFOOD,
    defaultUnit: Unit.WHOLE,
  },
  {
    id: 'blue_crab',
    krLabel: '꽃게',
    enLabel: 'Blue Crab',
    emoji: '🦀',
    category: Category.SEAFOOD,
    defaultUnit: Unit.WHOLE,
  },
  {
    id: 'snow_crab',
    krLabel: '대게',
    enLabel: 'Snow Crab',
    emoji: '🦀',
    category: Category.SEAFOOD,
    defaultUnit: Unit.WHOLE,
  },
  {
    id: 'king_crab',
    krLabel: '킹크랩',
    enLabel: 'King Crab',
    emoji: '🦀',
    category: Category.SEAFOOD,
    defaultUnit: Unit.WHOLE,
  },
  {
    id: 'lobster',
    krLabel: '랍스터',
    enLabel: 'Lobster',
    emoji: '🦞',
    category: Category.SEAFOOD,
    defaultUnit: Unit.WHOLE,
  },
  {
    id: 'sea_cucumber',
    krLabel: '해삼',
    enLabel: 'Sea Cucumber',
    emoji: '🦪',
    category: Category.SEAFOOD,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'sea_squirt',
    krLabel: '멍게',
    enLabel: 'Sea Squirt',
    emoji: '🦪',
    category: Category.SEAFOOD,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'sea_urchin',
    krLabel: '성게',
    enLabel: 'Sea Urchin',
    emoji: '🦪',
    category: Category.SEAFOOD,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'oyster',
    krLabel: '굴',
    enLabel: 'Oyster',
    emoji: '🦪',
    category: Category.SEAFOOD,
    defaultUnit: Unit.GRAM,
  },

  // 유제품
  {
    id: 'milk',
    krLabel: '우유',
    enLabel: 'Milk',
    emoji: '🥛',
    category: Category.DAIRY,
    defaultUnit: Unit.MILLILITER,
  },
  {
    id: 'low_fat_milk',
    krLabel: '저지방우유',
    enLabel: 'Low-fat Milk',
    emoji: '🥛',
    category: Category.DAIRY,
    defaultUnit: Unit.MILLILITER,
  },
  {
    id: 'soy_milk',
    krLabel: '두유',
    enLabel: 'Soy Milk',
    emoji: '🥛',
    category: Category.DAIRY,
    defaultUnit: Unit.MILLILITER,
  },
  {
    id: 'cheese',
    krLabel: '치즈',
    enLabel: 'Cheese',
    emoji: '🧀',
    category: Category.DAIRY,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'yogurt',
    krLabel: '요거트',
    enLabel: 'Yogurt',
    emoji: '🥛',
    category: Category.DAIRY,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'greek_yogurt',
    krLabel: '그릭요거트',
    enLabel: 'Greek Yogurt',
    emoji: '🥛',
    category: Category.DAIRY,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'butter',
    krLabel: '버터',
    enLabel: 'Butter',
    emoji: '🧈',
    category: Category.DAIRY,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'unsalted_butter',
    krLabel: '무염버터',
    enLabel: 'Unsalted Butter',
    emoji: '🧈',
    category: Category.DAIRY,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'egg',
    krLabel: '계란',
    enLabel: 'Egg',
    emoji: '🥚',
    category: Category.DAIRY,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'fresh_cream',
    krLabel: '생크림',
    enLabel: 'Fresh Cream',
    emoji: '🥛',
    category: Category.DAIRY,
    defaultUnit: Unit.MILLILITER,
  },
  {
    id: 'whipping_cream',
    krLabel: '휘핑크림',
    enLabel: 'Whipping Cream',
    emoji: '🥛',
    category: Category.DAIRY,
    defaultUnit: Unit.MILLILITER,
  },
  {
    id: 'sour_cream',
    krLabel: '사워크림',
    enLabel: 'Sour Cream',
    emoji: '🥛',
    category: Category.DAIRY,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'cream_cheese',
    krLabel: '크림치즈',
    enLabel: 'Cream Cheese',
    emoji: '🧀',
    category: Category.DAIRY,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'mozzarella',
    krLabel: '모짜렐라',
    enLabel: 'Mozzarella',
    emoji: '🧀',
    category: Category.DAIRY,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'cheddar_cheese',
    krLabel: '체다치즈',
    enLabel: 'Cheddar Cheese',
    emoji: '🧀',
    category: Category.DAIRY,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'parmesan',
    krLabel: '파르메산',
    enLabel: 'Parmesan',
    emoji: '🧀',
    category: Category.DAIRY,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'gorgonzola',
    krLabel: '고르곤졸라',
    enLabel: 'Gorgonzola',
    emoji: '🧀',
    category: Category.DAIRY,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'sliced_cheese',
    krLabel: '슬라이스치즈',
    enLabel: 'Sliced Cheese',
    emoji: '🧀',
    category: Category.DAIRY,
    defaultUnit: Unit.SHEET,
  },
  {
    id: 'condensed_milk',
    krLabel: '연유',
    enLabel: 'Condensed Milk',
    emoji: '🥛',
    category: Category.DAIRY,
    defaultUnit: Unit.MILLILITER,
  },

  // 가공 식품
  {
    id: 'tuna_can',
    krLabel: '참치캔',
    enLabel: 'Canned Tuna',
    emoji: '🥫',
    category: Category.PROCESSED,
    defaultUnit: Unit.CAN,
  },
  {
    id: 'bread',
    krLabel: '빵',
    enLabel: 'Bread',
    emoji: '🍞',
    category: Category.PROCESSED,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'white_bread',
    krLabel: '식빵',
    enLabel: 'White Bread',
    emoji: '🍞',
    category: Category.PROCESSED,
    defaultUnit: Unit.SHEET,
  },
  {
    id: 'baguette',
    krLabel: '바게트',
    enLabel: 'Baguette',
    emoji: '🥖',
    category: Category.PROCESSED,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'croissant',
    krLabel: '크루아상',
    enLabel: 'Croissant',
    emoji: '🥐',
    category: Category.PROCESSED,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'bagel',
    krLabel: '베이글',
    enLabel: 'Bagel',
    emoji: '🥯',
    category: Category.PROCESSED,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'instant_cooked_rice',
    krLabel: '즉석밥',
    enLabel: 'Instant Cooked Rice',
    emoji: '🍚',
    category: Category.PROCESSED,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'rice',
    krLabel: '쌀',
    enLabel: 'Rice',
    emoji: '🍚',
    category: Category.PROCESSED,
    defaultUnit: Unit.KILOGRAM,
  },
  {
    id: 'glutinous_rice',
    krLabel: '찹쌀',
    enLabel: 'Glutinous Rice',
    emoji: '🍚',
    category: Category.PROCESSED,
    defaultUnit: Unit.KILOGRAM,
  },
  {
    id: 'brown_rice',
    krLabel: '현미',
    enLabel: 'Brown Rice',
    emoji: '🍚',
    category: Category.PROCESSED,
    defaultUnit: Unit.KILOGRAM,
  },
  {
    id: 'barley',
    krLabel: '보리',
    enLabel: 'Barley',
    emoji: '🌾',
    category: Category.PROCESSED,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'oats',
    krLabel: '귀리',
    enLabel: 'Oats',
    emoji: '🌾',
    category: Category.PROCESSED,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'tofu',
    krLabel: '두부',
    enLabel: 'Tofu',
    emoji: '🍥',
    category: Category.PROCESSED,
    defaultUnit: Unit.PLANT,
  },
  {
    id: 'soft_tofu',
    krLabel: '순두부',
    enLabel: 'Soft Tofu',
    emoji: '🍥',
    category: Category.PROCESSED,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'fried_tofu',
    krLabel: '유부',
    enLabel: 'Fried Tofu',
    emoji: '🍥',
    category: Category.PROCESSED,
    defaultUnit: Unit.SHEET,
  },
  {
    id: 'seaweed',
    krLabel: '김',
    enLabel: 'Seaweed',
    emoji: '🍥',
    category: Category.PROCESSED,
    defaultUnit: Unit.SHEET,
  },
  {
    id: 'gimbap_seaweed',
    krLabel: '김밥김',
    enLabel: 'Gimbap Seaweed',
    emoji: '🍥',
    category: Category.PROCESSED,
    defaultUnit: Unit.SHEET,
  },
  {
    id: 'salad',
    krLabel: '샐러드',
    enLabel: 'Salad',
    emoji: '🥗',
    category: Category.VEGETABLE,
    defaultUnit: Unit.PACK,
  },
  {
    id: 'green_laver',
    krLabel: '파래',
    enLabel: 'Green Laver',
    emoji: '🌿',
    category: Category.PROCESSED,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'kelp',
    krLabel: '다시마',
    enLabel: 'Kelp',
    emoji: '🍥',
    category: Category.PROCESSED,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'sea_mustard',
    krLabel: '미역',
    enLabel: 'Sea Mustard',
    emoji: '🍥',
    category: Category.PROCESSED,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'ramen',
    krLabel: '라면',
    enLabel: 'Instant Noodles',
    emoji: '🍜',
    category: Category.PROCESSED,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'frozen_dumplings',
    krLabel: '냉동만두',
    enLabel: 'Frozen Dumplings',
    emoji: '🥟',
    category: Category.PROCESSED,
    defaultUnit: Unit.PACK,
  },
  {
    id: 'chapagetti',
    krLabel: '짜파게티',
    enLabel: 'Chapagetti',
    emoji: '🍜',
    category: Category.PROCESSED,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'kimchi',
    krLabel: '김치',
    enLabel: 'Kimchi',
    emoji: '🥬',
    category: Category.PROCESSED,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'kkakdugi',
    krLabel: '깍두기',
    enLabel: 'Cubed Radish Kimchi',
    emoji: '🥬',
    category: Category.PROCESSED,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'baechu_kimchi',
    krLabel: '배추김치',
    enLabel: 'Napa Cabbage Kimchi',
    emoji: '🥬',
    category: Category.PROCESSED,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'doenjang',
    krLabel: '된장',
    enLabel: 'Soybean Paste',
    emoji: '🥫',
    category: Category.PROCESSED,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'gochujang',
    krLabel: '고추장',
    enLabel: 'Red Chili Paste',
    emoji: '🥫',
    category: Category.PROCESSED,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'ssamjang',
    krLabel: '쌈장',
    enLabel: 'Ssamjang',
    emoji: '🥫',
    category: Category.PROCESSED,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'cheonggukjang',
    krLabel: '청국장',
    enLabel: 'Fermented Soybean Paste',
    emoji: '🥫',
    category: Category.PROCESSED,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'sesame_oil',
    krLabel: '참기름',
    enLabel: 'Sesame Oil',
    emoji: '🛢️',
    category: Category.PROCESSED,
    defaultUnit: Unit.MILLILITER,
  },
  {
    id: 'perilla_oil',
    krLabel: '들기름',
    enLabel: 'Perilla Oil',
    emoji: '🛢️',
    category: Category.PROCESSED,
    defaultUnit: Unit.MILLILITER,
  },
  {
    id: 'cooking_oil',
    krLabel: '식용유',
    enLabel: 'Cooking Oil',
    emoji: '🛢️',
    category: Category.PROCESSED,
    defaultUnit: Unit.MILLILITER,
  },
  {
    id: 'olive_oil',
    krLabel: '올리브유',
    enLabel: 'Olive Oil',
    emoji: '🫒',
    category: Category.PROCESSED,
    defaultUnit: Unit.MILLILITER,
  },
  {
    id: 'grapeseed_oil',
    krLabel: '포도씨유',
    enLabel: 'Grapeseed Oil',
    emoji: '🛢️',
    category: Category.PROCESSED,
    defaultUnit: Unit.MILLILITER,
  },
  {
    id: 'canola_oil',
    krLabel: '카놀라유',
    enLabel: 'Canola Oil',
    emoji: '🛢️',
    category: Category.PROCESSED,
    defaultUnit: Unit.MILLILITER,
  },

  // 조미료
  {
    id: 'salt',
    krLabel: '소금',
    enLabel: 'Salt',
    emoji: '🧂',
    category: Category.SEASONING,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'coarse_salt',
    krLabel: '굵은소금',
    enLabel: 'Coarse Salt',
    emoji: '🧂',
    category: Category.SEASONING,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'flower_salt',
    krLabel: '꽃소금',
    enLabel: 'Flower Salt',
    emoji: '🧂',
    category: Category.SEASONING,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'sugar',
    krLabel: '설탕',
    enLabel: 'Sugar',
    emoji: '🧂',
    category: Category.SEASONING,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'brown_sugar',
    krLabel: '흑설탕',
    enLabel: 'Brown Sugar',
    emoji: '🧂',
    category: Category.SEASONING,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'oligosaccharide',
    krLabel: '올리고당',
    enLabel: 'Oligosaccharide',
    emoji: '🍯',
    category: Category.SEASONING,
    defaultUnit: Unit.MILLILITER,
  },
  {
    id: 'honey',
    krLabel: '꿀',
    enLabel: 'Honey',
    emoji: '🍯',
    category: Category.SEASONING,
    defaultUnit: Unit.MILLILITER,
  },
  {
    id: 'starch_syrup',
    krLabel: '물엿',
    enLabel: 'Starch Syrup',
    emoji: '🍯',
    category: Category.SEASONING,
    defaultUnit: Unit.MILLILITER,
  },
  {
    id: 'rice_syrup',
    krLabel: '조청',
    enLabel: 'Rice Syrup',
    emoji: '🍯',
    category: Category.SEASONING,
    defaultUnit: Unit.MILLILITER,
  },
  {
    id: 'soy_sauce',
    krLabel: '간장',
    enLabel: 'Soy Sauce',
    emoji: '🥫',
    category: Category.SEASONING,
    defaultUnit: Unit.MILLILITER,
  },
  {
    id: 'dark_soy_sauce',
    krLabel: '진간장',
    enLabel: 'Dark Soy Sauce',
    emoji: '🥫',
    category: Category.SEASONING,
    defaultUnit: Unit.MILLILITER,
  },
  {
    id: 'soup_soy_sauce',
    krLabel: '국간장',
    enLabel: 'Soup Soy Sauce',
    emoji: '🥫',
    category: Category.SEASONING,
    defaultUnit: Unit.MILLILITER,
  },
  {
    id: 'brewed_soy_sauce',
    krLabel: '양조간장',
    enLabel: 'Brewed Soy Sauce',
    emoji: '🥫',
    category: Category.SEASONING,
    defaultUnit: Unit.MILLILITER,
  },
  {
    id: 'vinegar',
    krLabel: '식초',
    enLabel: 'Vinegar',
    emoji: '🧴',
    category: Category.SEASONING,
    defaultUnit: Unit.MILLILITER,
  },
  {
    id: 'apple_vinegar',
    krLabel: '사과식초',
    enLabel: 'Apple Vinegar',
    emoji: '🧴',
    category: Category.SEASONING,
    defaultUnit: Unit.MILLILITER,
  },
  {
    id: 'brown_rice_vinegar',
    krLabel: '현미식초',
    enLabel: 'Brown Rice Vinegar',
    emoji: '🧴',
    category: Category.SEASONING,
    defaultUnit: Unit.MILLILITER,
  },
  {
    id: 'red_pepper_powder',
    krLabel: '고춧가루',
    enLabel: 'Red Pepper Powder',
    emoji: '🌶️',
    category: Category.SEASONING,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'fine_red_pepper_powder',
    krLabel: '고운고춧가루',
    enLabel: 'Fine Red Pepper Powder',
    emoji: '🌶️',
    category: Category.SEASONING,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'coarse_red_pepper_powder',
    krLabel: '굵은고춧가루',
    enLabel: 'Coarse Red Pepper Powder',
    emoji: '🌶️',
    category: Category.SEASONING,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'black_pepper',
    krLabel: '후추',
    enLabel: 'Black Pepper',
    emoji: '🧂',
    category: Category.SEASONING,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'whole_pepper',
    krLabel: '통후추',
    enLabel: 'Whole Pepper',
    emoji: '🧂',
    category: Category.SEASONING,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'white_pepper',
    krLabel: '흰후추',
    enLabel: 'White Pepper',
    emoji: '🧂',
    category: Category.SEASONING,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'minced_garlic',
    krLabel: '다진마늘',
    enLabel: 'Minced Garlic',
    emoji: '🧄',
    category: Category.SEASONING,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'garlic_powder',
    krLabel: '마늘가루',
    enLabel: 'Garlic Powder',
    emoji: '🧄',
    category: Category.SEASONING,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'ginger_powder',
    krLabel: '생강가루',
    enLabel: 'Ginger Powder',
    emoji: '🫚',
    category: Category.SEASONING,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'mirin',
    krLabel: '맛술',
    enLabel: 'Cooking Wine (Mirin)',
    emoji: '🍶',
    category: Category.SEASONING,
    defaultUnit: Unit.MILLILITER,
  },
  {
    id: 'cheongju',
    krLabel: '청주',
    enLabel: 'Cheongju',
    emoji: '🍶',
    category: Category.SEASONING,
    defaultUnit: Unit.MILLILITER,
  },
  {
    id: 'mirim',
    krLabel: '미림',
    enLabel: 'Mirim',
    emoji: '🍶',
    category: Category.SEASONING,
    defaultUnit: Unit.MILLILITER,
  },
  {
    id: 'oyster_sauce',
    krLabel: '굴소스',
    enLabel: 'Oyster Sauce',
    emoji: '🥫',
    category: Category.SEASONING,
    defaultUnit: Unit.MILLILITER,
  },
  {
    id: 'fish_sauce',
    krLabel: '피시소스',
    enLabel: 'Fish Sauce',
    emoji: '🥫',
    category: Category.SEASONING,
    defaultUnit: Unit.MILLILITER,
  },
  {
    id: 'ketchup',
    krLabel: '케첩',
    enLabel: 'Ketchup',
    emoji: '🥫',
    category: Category.SEASONING,
    defaultUnit: Unit.MILLILITER,
  },
  {
    id: 'tomato_sauce',
    krLabel: '토마토소스',
    enLabel: 'Tomato Sauce',
    emoji: '🍅',
    category: Category.SEASONING,
    defaultUnit: Unit.MILLILITER,
  },
  {
    id: 'tomato_paste',
    krLabel: '토마토페이스트',
    enLabel: 'Tomato Paste',
    emoji: '🍅',
    category: Category.SEASONING,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'mayonnaise',
    krLabel: '마요네즈',
    enLabel: 'Mayonnaise',
    emoji: '🥫',
    category: Category.SEASONING,
    defaultUnit: Unit.MILLILITER,
  },
  {
    id: 'mustard',
    krLabel: '머스타드',
    enLabel: 'Mustard',
    emoji: '🥫',
    category: Category.SEASONING,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'yellow_mustard',
    krLabel: '겨자',
    enLabel: 'Yellow Mustard',
    emoji: '🥫',
    category: Category.SEASONING,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'wasabi',
    krLabel: '와사비',
    enLabel: 'Wasabi',
    emoji: '🥫',
    category: Category.SEASONING,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'curry_powder',
    krLabel: '카레가루',
    enLabel: 'Curry Powder',
    emoji: '🍛',
    category: Category.SEASONING,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'curry_block',
    krLabel: '카레블럭',
    enLabel: 'Curry Block',
    emoji: '🍛',
    category: Category.SEASONING,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'chunjang',
    krLabel: '춘장',
    enLabel: 'Chunjang',
    emoji: '🥫',
    category: Category.SEASONING,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'pork_cutlet_sauce',
    krLabel: '돈까스소스',
    enLabel: 'Pork Cutlet Sauce',
    emoji: '🥫',
    category: Category.SEASONING,
    defaultUnit: Unit.MILLILITER,
  },
  {
    id: 'worcestershire_sauce',
    krLabel: '우스터소스',
    enLabel: 'Worcestershire Sauce',
    emoji: '🥫',
    category: Category.SEASONING,
    defaultUnit: Unit.MILLILITER,
  },
  {
    id: 'tabasco',
    krLabel: '타바스코',
    enLabel: 'Tabasco',
    emoji: '🌶️',
    category: Category.SEASONING,
    defaultUnit: Unit.MILLILITER,
  },
  {
    id: 'chili_sauce',
    krLabel: '칠리소스',
    enLabel: 'Chili Sauce',
    emoji: '🌶️',
    category: Category.SEASONING,
    defaultUnit: Unit.MILLILITER,
  },
  {
    id: 'sriracha',
    krLabel: '스리라차',
    enLabel: 'Sriracha',
    emoji: '🌶️',
    category: Category.SEASONING,
    defaultUnit: Unit.MILLILITER,
  },
  {
    id: 'sesame',
    krLabel: '참깨',
    enLabel: 'Sesame',
    emoji: '⚪',
    category: Category.SEASONING,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'perilla_seed',
    krLabel: '들깨',
    enLabel: 'Perilla Seed',
    emoji: '⚪',
    category: Category.SEASONING,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'perilla_powder',
    krLabel: '들깨가루',
    enLabel: 'Perilla Powder',
    emoji: '⚪',
    category: Category.SEASONING,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'whole_sesame',
    krLabel: '통깨',
    enLabel: 'Whole Sesame',
    emoji: '⚪',
    category: Category.SEASONING,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'sesame_salt',
    krLabel: '깨소금',
    enLabel: 'Sesame Salt',
    emoji: '⚪',
    category: Category.SEASONING,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'basil',
    krLabel: '바질',
    enLabel: 'Basil',
    emoji: '🌿',
    category: Category.SEASONING,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'rosemary',
    krLabel: '로즈마리',
    enLabel: 'Rosemary',
    emoji: '🌿',
    category: Category.SEASONING,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'thyme',
    krLabel: '타임',
    enLabel: 'Thyme',
    emoji: '🌿',
    category: Category.SEASONING,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'oregano',
    krLabel: '오레가노',
    enLabel: 'Oregano',
    emoji: '🌿',
    category: Category.SEASONING,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'parsley',
    krLabel: '파슬리',
    enLabel: 'Parsley',
    emoji: '🌿',
    category: Category.SEASONING,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'coriander',
    krLabel: '고수',
    enLabel: 'Coriander',
    emoji: '🌿',
    category: Category.SEASONING,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'cinnamon',
    krLabel: '계피',
    enLabel: 'Cinnamon',
    emoji: '🟤',
    category: Category.SEASONING,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'star_anise',
    krLabel: '팔각',
    enLabel: 'Star Anise',
    emoji: '⭐',
    category: Category.SEASONING,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'bay_leaf',
    krLabel: '월계수잎',
    enLabel: 'Bay Leaf',
    emoji: '🍃',
    category: Category.SEASONING,
    defaultUnit: Unit.SHEET,
  },
  {
    id: 'stock_pack',
    krLabel: '육수팩',
    enLabel: 'Stock Pack',
    emoji: '🥫',
    category: Category.SEASONING,
    defaultUnit: Unit.PIECE,
  },
  {
    id: 'dashida',
    krLabel: '다시다',
    enLabel: 'Dashida',
    emoji: '🥫',
    category: Category.SEASONING,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'anchovy_sauce',
    krLabel: '멸치액젓',
    enLabel: 'Anchovy Sauce',
    emoji: '🥫',
    category: Category.SEASONING,
    defaultUnit: Unit.MILLILITER,
  },
  {
    id: 'sand_lance_sauce',
    krLabel: '까나리액젓',
    enLabel: 'Sand Lance Sauce',
    emoji: '🥫',
    category: Category.SEASONING,
    defaultUnit: Unit.MILLILITER,
  },
  {
    id: 'salted_shrimp',
    krLabel: '새우젓',
    enLabel: 'Salted Shrimp',
    emoji: '🦐',
    category: Category.SEASONING,
    defaultUnit: Unit.GRAM,
  },
  {
    id: 'msg',
    krLabel: 'MSG',
    enLabel: 'MSG',
    emoji: '🧂',
    category: Category.SEASONING,
    defaultUnit: Unit.GRAM,
  },
];

export function getTemplatesByCategory(category: Category | null): IngredientTemplate[] {
  if (!category) {
    return ingredientTemplates;
  }

  return ingredientTemplates.filter((item) => item.category === category);
}

/**
 * 각 카테고리별 이모지 후보 목록 (5개씩)
 */
export const categoryEmojiOptions: Record<Category, string[]> = {
  [Category.ALL]: ['📦', '🗂️', '📋', '🏪', '🛒'],
  [Category.VEGETABLE]: ['🥬', '🥦', '🥕', '🌽', '🍆'],
  [Category.FRUIT]: ['🍎', '🍊', '🍇', '🍓', '🍌'],
  [Category.MEAT]: ['🥩', '🍖', '🥓', '🍗', '🦴'],
  [Category.SEAFOOD]: ['🐟', '🦐', '🦀', '🐙', '🦑'],
  [Category.DAIRY]: ['🥛', '🧀', '🧈', '🍼', '🥚'],
  [Category.PROCESSED]: ['🍽️', '🥫', '🍱', '🥡', '🍜'],
  [Category.SEASONING]: ['🧂', '🧄', '🌶️', '🫚', '🧉'],
  [Category.OTHER]: ['🍴', '🔪', '🥄', '🍽️', '🥢'],
};

/**
 * 카테고리별 기본 이모지 (첫 번째 옵션)
 */
export const categoryDefaultEmojis: Record<Category, string> = {
  [Category.ALL]: categoryEmojiOptions[Category.ALL][0],
  [Category.VEGETABLE]: categoryEmojiOptions[Category.VEGETABLE][0],
  [Category.FRUIT]: categoryEmojiOptions[Category.FRUIT][0],
  [Category.MEAT]: categoryEmojiOptions[Category.MEAT][0],
  [Category.SEAFOOD]: categoryEmojiOptions[Category.SEAFOOD][0],
  [Category.DAIRY]: categoryEmojiOptions[Category.DAIRY][0],
  [Category.PROCESSED]: categoryEmojiOptions[Category.PROCESSED][0],
  [Category.SEASONING]: categoryEmojiOptions[Category.SEASONING][0],
  [Category.OTHER]: categoryEmojiOptions[Category.OTHER][0],
};

/**
 * 카테고리에 해당하는 랜덤 이모지 반환
 */
export function getRandomEmojiForCategory(category: Category): string {
  const emojis = categoryEmojiOptions[category];
  const randomIndex = Math.floor(Math.random() * emojis.length);
  return emojis[randomIndex];
}
