export interface IngredientTemplate {
  name: string;
  emoji: string;
  category: string;
  defaultUnit?: string;
}

export const ingredientTemplates: IngredientTemplate[] = [
  // 채소
  { name: '당근', emoji: '🥕', category: '채소', defaultUnit: '개' },
  { name: '양파', emoji: '🧅', category: '채소', defaultUnit: '개' },
  { name: '감자', emoji: '🥔', category: '채소', defaultUnit: '개' },
  { name: '토마토', emoji: '🍅', category: '채소', defaultUnit: '개' },
  { name: '상추', emoji: '🥬', category: '채소', defaultUnit: 'g' },
  { name: '배추', emoji: '🥬', category: '채소', defaultUnit: '포기' },
  { name: '브로콜리', emoji: '🥦', category: '채소', defaultUnit: '개' },
  { name: '오이', emoji: '🥒', category: '채소', defaultUnit: '개' },
  { name: '가지', emoji: '🍆', category: '채소', defaultUnit: '개' },
  { name: '피망', emoji: '🫑', category: '채소', defaultUnit: '개' },
  { name: '옥수수', emoji: '🌽', category: '채소', defaultUnit: '개' },
  { name: '버섯', emoji: '🍄', category: '채소', defaultUnit: 'g' },
  { name: '표고버섯', emoji: '🍄‍🟫', category: '채소', defaultUnit: 'g' },
  { name: '느타리버섯', emoji: '🍄', category: '채소', defaultUnit: 'g' },
  { name: '팽이버섯', emoji: '🍄', category: '채소', defaultUnit: 'g' },
  { name: '새송이버섯', emoji: '🍄', category: '채소', defaultUnit: '개' },
  { name: '양송이버섯', emoji: '🍄', category: '채소', defaultUnit: 'g' },
  { name: '대파', emoji: '🧅', category: '채소', defaultUnit: '개' },
  { name: '쪽파', emoji: '🧅', category: '채소', defaultUnit: '개' },
  { name: '마늘', emoji: '🧄', category: '채소', defaultUnit: '개' },
  { name: '생강', emoji: '🫚', category: '채소', defaultUnit: 'g' },
  { name: '고추', emoji: '🌶️', category: '채소', defaultUnit: '개' },
  { name: '깻잎', emoji: '🍃', category: '채소', defaultUnit: '장' },
  { name: '시금치', emoji: '🥬', category: '채소', defaultUnit: 'g' },
  { name: '무', emoji: '🥕', category: '채소', defaultUnit: '개' },
  { name: '알타리무', emoji: '🥕', category: '채소', defaultUnit: '개' },
  { name: '애호박', emoji: '🥒', category: '채소', defaultUnit: '개' },
  { name: '청양고추', emoji: '🌶️', category: '채소', defaultUnit: '개' },
  { name: '파프리카', emoji: '🫑', category: '채소', defaultUnit: '개' },
  { name: '콩나물', emoji: '🌱', category: '채소', defaultUnit: 'g' },
  { name: '숙주', emoji: '🌱', category: '채소', defaultUnit: 'g' },
  { name: '미나리', emoji: '🌿', category: '채소', defaultUnit: 'g' },
  { name: '부추', emoji: '🌿', category: '채소', defaultUnit: 'g' },
  { name: '쑥갓', emoji: '🌿', category: '채소', defaultUnit: 'g' },
  { name: '케일', emoji: '🥬', category: '채소', defaultUnit: 'g' },
  { name: '양배추', emoji: '🥬', category: '채소', defaultUnit: '개' },
  { name: '청경채', emoji: '🥬', category: '채소', defaultUnit: '개' },
  { name: '콜리플라워', emoji: '🥦', category: '채소', defaultUnit: '개' },
  { name: '아스파라거스', emoji: '🥒', category: '채소', defaultUnit: 'g' },
  { name: '셀러리', emoji: '🥬', category: '채소', defaultUnit: '개' },
  { name: '연근', emoji: '🪷', category: '채소', defaultUnit: 'g' },
  { name: '우엉', emoji: '🥕', category: '채소', defaultUnit: 'g' },
  { name: '도라지', emoji: '🌿', category: '채소', defaultUnit: 'g' },
  { name: '고구마', emoji: '🍠', category: '채소', defaultUnit: '개' },
  { name: '단호박', emoji: '🎃', category: '채소', defaultUnit: '개' },
  { name: '늙은호박', emoji: '🎃', category: '채소', defaultUnit: '개' },

  // 과일
  { name: '사과', emoji: '🍎', category: '과일', defaultUnit: '개' },
  { name: '바나나', emoji: '🍌', category: '과일', defaultUnit: '개' },
  { name: '오렌지', emoji: '🍊', category: '과일', defaultUnit: '개' },
  { name: '딸기', emoji: '🍓', category: '과일', defaultUnit: 'g' },
  { name: '포도', emoji: '🍇', category: '과일', defaultUnit: '송이' },
  { name: '샤인머스캣', emoji: '🍇', category: '과일', defaultUnit: '송이' },
  { name: '수박', emoji: '🍉', category: '과일', defaultUnit: '개' },
  { name: '복숭아', emoji: '🍑', category: '과일', defaultUnit: '개' },
  { name: '키위', emoji: '🥝', category: '과일', defaultUnit: '개' },
  { name: '망고', emoji: '🥭', category: '과일', defaultUnit: '개' },
  { name: '파인애플', emoji: '🍍', category: '과일', defaultUnit: '개' },
  { name: '레몬', emoji: '🍋', category: '과일', defaultUnit: '개' },
  { name: '라임', emoji: '🍋‍🟩', category: '과일', defaultUnit: '개' },
  { name: '체리', emoji: '🍒', category: '과일', defaultUnit: 'g' },
  { name: '배', emoji: '�梨', category: '과일', defaultUnit: '개' },
  { name: '귤', emoji: '🍊', category: '과일', defaultUnit: '개' },
  { name: '한라봉', emoji: '🍊', category: '과일', defaultUnit: '개' },
  { name: '천혜향', emoji: '🍊', category: '과일', defaultUnit: '개' },
  { name: '자두', emoji: '🍑', category: '과일', defaultUnit: '개' },
  { name: '참외', emoji: '🍈', category: '과일', defaultUnit: '개' },
  { name: '메론', emoji: '🍈', category: '과일', defaultUnit: '개' },
  { name: '블루베리', emoji: '🫐', category: '과일', defaultUnit: 'g' },
  { name: '아보카도', emoji: '🥑', category: '과일', defaultUnit: '개' },
  { name: '감', emoji: '🟠', category: '과일', defaultUnit: '개' },
  { name: '곶감', emoji: '🟠', category: '과일', defaultUnit: '개' },
  { name: '대추', emoji: '🫒', category: '과일', defaultUnit: 'g' },
  { name: '자몽', emoji: '🍊', category: '과일', defaultUnit: '개' },
  { name: '용과', emoji: '🐉', category: '과일', defaultUnit: '개' },
  { name: '두리안', emoji: '🥥', category: '과일', defaultUnit: '개' },
  { name: '코코넛', emoji: '🥥', category: '과일', defaultUnit: '개' },
  { name: '패션후르츠', emoji: '🥝', category: '과일', defaultUnit: '개' },
  { name: '올리브', emoji: '🫒', category: '과일', defaultUnit: 'g' },

  // 육류
  { name: '소고기', emoji: '🥩', category: '육류', defaultUnit: 'g' },
  { name: '돼지고기', emoji: '🥓', category: '육류', defaultUnit: 'g' },
  { name: '닭고기', emoji: '🍗', category: '육류', defaultUnit: 'g' },
  { name: '삼겹살', emoji: '🥓', category: '육류', defaultUnit: 'g' },
  { name: '목살', emoji: '🥩', category: '육류', defaultUnit: 'g' },
  { name: '안심', emoji: '🥩', category: '육류', defaultUnit: 'g' },
  { name: '등심', emoji: '🥩', category: '육류', defaultUnit: 'g' },
  { name: '채끝', emoji: '🥩', category: '육류', defaultUnit: 'g' },
  { name: '양지', emoji: '🥩', category: '육류', defaultUnit: 'g' },
  { name: '사태', emoji: '🥩', category: '육류', defaultUnit: 'g' },
  { name: '우둔', emoji: '🥩', category: '육류', defaultUnit: 'g' },
  { name: '갈비', emoji: '🥩', category: '육류', defaultUnit: 'g' },
  { name: '닭가슴살', emoji: '🍗', category: '육류', defaultUnit: 'g' },
  { name: '닭다리', emoji: '🍗', category: '육류', defaultUnit: '개' },
  { name: '닭날개', emoji: '🍗', category: '육류', defaultUnit: '개' },
  { name: '오리고기', emoji: '🦆', category: '육류', defaultUnit: 'g' },
  { name: '베이컨', emoji: '🥓', category: '육류', defaultUnit: 'g' },
  { name: '소시지', emoji: '🌭', category: '육류', defaultUnit: '개' },
  { name: '햄', emoji: '🍖', category: '육류', defaultUnit: 'g' },
  { name: '스팸', emoji: '🥫', category: '육류', defaultUnit: '개' },
  { name: '다진소고기', emoji: '🥩', category: '육류', defaultUnit: 'g' },
  { name: '다진돼지고기', emoji: '🥓', category: '육류', defaultUnit: 'g' },
  { name: '양고기', emoji: '🍖', category: '육류', defaultUnit: 'g' },

  // 생선류
  { name: '고등어', emoji: '🐟', category: '생선류', defaultUnit: '마리' },
  { name: '연어', emoji: '🐟', category: '생선류', defaultUnit: 'g' },
  { name: '참치', emoji: '🐟', category: '생선류', defaultUnit: '캔' },
  { name: '광어', emoji: '🐟', category: '생선류', defaultUnit: '마리' },
  { name: '우럭', emoji: '🐟', category: '생선류', defaultUnit: '마리' },
  { name: '도미', emoji: '🐟', category: '생선류', defaultUnit: '마리' },
  { name: '오징어', emoji: '🦑', category: '생선류', defaultUnit: '마리' },
  { name: '문어', emoji: '🐙', category: '생선류', defaultUnit: '마리' },
  { name: '낙지', emoji: '🐙', category: '생선류', defaultUnit: '마리' },
  { name: '주꾸미', emoji: '🐙', category: '생선류', defaultUnit: '마리' },
  { name: '새우', emoji: '🦐', category: '생선류', defaultUnit: 'g' },
  { name: '대하', emoji: '🦐', category: '생선류', defaultUnit: '마리' },
  { name: '조기', emoji: '🐟', category: '생선류', defaultUnit: '마리' },
  { name: '갈치', emoji: '🐟', category: '생선류', defaultUnit: '마리' },
  { name: '꽁치', emoji: '🐟', category: '생선류', defaultUnit: '마리' },
  { name: '삼치', emoji: '🐟', category: '생선류', defaultUnit: '마리' },
  { name: '방어', emoji: '🐟', category: '생선류', defaultUnit: '마리' },
  { name: '멸치', emoji: '🐟', category: '생선류', defaultUnit: 'g' },
  { name: '국물멸치', emoji: '🐟', category: '생선류', defaultUnit: 'g' },
  { name: '볶음멸치', emoji: '🐟', category: '생선류', defaultUnit: 'g' },
  { name: '명태', emoji: '🐟', category: '생선류', defaultUnit: '마리' },
  { name: '북어', emoji: '🐟', category: '생선류', defaultUnit: '마리' },
  { name: '황태', emoji: '🐟', category: '생선류', defaultUnit: '마리' },
  { name: '조개', emoji: '🦪', category: '생선류', defaultUnit: 'g' },
  { name: '바지락', emoji: '🦪', category: '생선류', defaultUnit: 'g' },
  { name: '모시조개', emoji: '🦪', category: '생선류', defaultUnit: 'g' },
  { name: '키조개', emoji: '🦪', category: '생선류', defaultUnit: '개' },
  { name: '가리비', emoji: '🦪', category: '생선류', defaultUnit: '개' },
  { name: '홍합', emoji: '🦪', category: '생선류', defaultUnit: 'g' },
  { name: '전복', emoji: '🦪', category: '생선류', defaultUnit: '개' },
  { name: '소라', emoji: '🐚', category: '생선류', defaultUnit: '개' },
  { name: '골뱅이', emoji: '🐚', category: '생선류', defaultUnit: '캔' },
  { name: '게', emoji: '🦀', category: '생선류', defaultUnit: '마리' },
  { name: '꽃게', emoji: '🦀', category: '생선류', defaultUnit: '마리' },
  { name: '대게', emoji: '🦀', category: '생선류', defaultUnit: '마리' },
  { name: '킹크랩', emoji: '🦀', category: '생선류', defaultUnit: '마리' },
  { name: '랍스터', emoji: '🦞', category: '생선류', defaultUnit: '마리' },
  { name: '해삼', emoji: '🦪', category: '생선류', defaultUnit: '개' },
  { name: '멍게', emoji: '🦪', category: '생선류', defaultUnit: '개' },
  { name: '성게', emoji: '🦪', category: '생선류', defaultUnit: '개' },
  { name: '굴', emoji: '🦪', category: '생선류', defaultUnit: 'g' },

  // 유제품
  { name: '우유', emoji: '🥛', category: '유제품', defaultUnit: 'ml' },
  { name: '저지방우유', emoji: '🥛', category: '유제품', defaultUnit: 'ml' },
  { name: '두유', emoji: '🥛', category: '유제품', defaultUnit: 'ml' },
  { name: '치즈', emoji: '🧀', category: '유제품', defaultUnit: 'g' },
  { name: '요거트', emoji: '🥛', category: '유제품', defaultUnit: '개' },
  { name: '그릭요거트', emoji: '🥛', category: '유제품', defaultUnit: '개' },
  { name: '버터', emoji: '🧈', category: '유제품', defaultUnit: 'g' },
  { name: '무염버터', emoji: '🧈', category: '유제품', defaultUnit: 'g' },
  { name: '계란', emoji: '🥚', category: '유제품', defaultUnit: '개' },
  { name: '생크림', emoji: '🥛', category: '유제품', defaultUnit: 'ml' },
  { name: '휘핑크림', emoji: '🥛', category: '유제품', defaultUnit: 'ml' },
  { name: '사워크림', emoji: '🥛', category: '유제품', defaultUnit: 'g' },
  { name: '크림치즈', emoji: '🧀', category: '유제품', defaultUnit: 'g' },
  { name: '모짜렐라', emoji: '🧀', category: '유제품', defaultUnit: 'g' },
  { name: '체다치즈', emoji: '🧀', category: '유제품', defaultUnit: 'g' },
  { name: '파르메산', emoji: '🧀', category: '유제품', defaultUnit: 'g' },
  { name: '고르곤졸라', emoji: '🧀', category: '유제품', defaultUnit: 'g' },
  { name: '슬라이스치즈', emoji: '🧀', category: '유제품', defaultUnit: '장' },
  { name: '연유', emoji: '🥛', category: '유제품', defaultUnit: 'ml' },

  // 가공식품
  { name: '빵', emoji: '🍞', category: '가공식품', defaultUnit: '개' },
  { name: '식빵', emoji: '🍞', category: '가공식품', defaultUnit: '장' },
  { name: '바게트', emoji: '🥖', category: '가공식품', defaultUnit: '개' },
  { name: '크루아상', emoji: '🥐', category: '가공식품', defaultUnit: '개' },
  { name: '베이글', emoji: '🥯', category: '가공식품', defaultUnit: '개' },
  { name: '쌀', emoji: '🍚', category: '가공식품', defaultUnit: 'kg' },
  { name: '찹쌀', emoji: '🍚', category: '가공식품', defaultUnit: 'kg' },
  { name: '현미', emoji: '🍚', category: '가공식품', defaultUnit: 'kg' },
  { name: '보리', emoji: '🌾', category: '가공식품', defaultUnit: 'g' },
  { name: '귀리', emoji: '🌾', category: '가공식품', defaultUnit: 'g' },
  { name: '두부', emoji: '🍥', category: '가공식품', defaultUnit: '모' },
  { name: '순두부', emoji: '🍥', category: '가공식품', defaultUnit: '개' },
  { name: '유부', emoji: '🍥', category: '가공식품', defaultUnit: '장' },
  { name: '김', emoji: '🍥', category: '가공식품', defaultUnit: '장' },
  { name: '김밥김', emoji: '🍥', category: '가공식품', defaultUnit: '장' },
  { name: '파래', emoji: '🌿', category: '가공식품', defaultUnit: 'g' },
  { name: '다시마', emoji: '🍥', category: '가공식품', defaultUnit: 'g' },
  { name: '미역', emoji: '🍥', category: '가공식품', defaultUnit: 'g' },
  { name: '라면', emoji: '🍜', category: '가공식품', defaultUnit: '개' },
  { name: '짜파게티', emoji: '🍜', category: '가공식품', defaultUnit: '개' },
  { name: '김치', emoji: '🥬', category: '가공식품', defaultUnit: 'g' },
  { name: '깍두기', emoji: '🥬', category: '가공식품', defaultUnit: 'g' },
  { name: '배추김치', emoji: '🥬', category: '가공식품', defaultUnit: 'g' },
  { name: '된장', emoji: '🥫', category: '가공식품', defaultUnit: 'g' },
  { name: '고추장', emoji: '🥫', category: '가공식품', defaultUnit: 'g' },
  { name: '쌈장', emoji: '🥫', category: '가공식품', defaultUnit: 'g' },
  { name: '청국장', emoji: '🥫', category: '가공식품', defaultUnit: 'g' },
  { name: '참기름', emoji: '🛢️', category: '가공식품', defaultUnit: 'ml' },
  { name: '들기름', emoji: '🛢️', category: '가공식품', defaultUnit: 'ml' },
  { name: '식용유', emoji: '🛢️', category: '가공식품', defaultUnit: 'ml' },
  { name: '올리브유', emoji: '🫒', category: '가공식품', defaultUnit: 'ml' },
  { name: '포도씨유', emoji: '🛢️', category: '가공식품', defaultUnit: 'ml' },
  { name: '카놀라유', emoji: '🛢️', category: '가공식품', defaultUnit: 'ml' },
  { name: '파스타', emoji: '🍝', category: '가공식품', defaultUnit: 'g' },
  { name: '스파게티면', emoji: '🍝', category: '가공식품', defaultUnit: 'g' },
  { name: '펜네', emoji: '🍝', category: '가공식품', defaultUnit: 'g' },
  { name: '국수', emoji: '🍜', category: '가공식품', defaultUnit: 'g' },
  { name: '소면', emoji: '🍜', category: '가공식품', defaultUnit: 'g' },
  { name: '당면', emoji: '🍜', category: '가공식품', defaultUnit: 'g' },
  { name: '쫄면', emoji: '🍜', category: '가공식품', defaultUnit: 'g' },
  { name: '우동면', emoji: '🍜', category: '가공식품', defaultUnit: 'g' },
  { name: '냉면', emoji: '🍜', category: '가공식품', defaultUnit: '개' },
  { name: '통조림', emoji: '🥫', category: '가공식품', defaultUnit: '개' },
  {
    name: '옥수수통조림',
    emoji: '🥫',
    category: '가공식품',
    defaultUnit: '캔',
  },
  { name: '참치캔', emoji: '🥫', category: '가공식품', defaultUnit: '캔' },
  { name: '콩', emoji: '🫘', category: '가공식품', defaultUnit: 'g' },
  { name: '완두콩', emoji: '🫛', category: '가공식품', defaultUnit: 'g' },
  { name: '강낭콩', emoji: '🫘', category: '가공식품', defaultUnit: 'g' },
  { name: '팥', emoji: '🫘', category: '가공식품', defaultUnit: 'g' },
  { name: '녹두', emoji: '🫘', category: '가공식품', defaultUnit: 'g' },
  { name: '견과류', emoji: '🥜', category: '가공식품', defaultUnit: 'g' },
  { name: '땅콩', emoji: '🥜', category: '가공식품', defaultUnit: 'g' },
  { name: '아몬드', emoji: '🥜', category: '가공식품', defaultUnit: 'g' },
  { name: '호두', emoji: '🥜', category: '가공식품', defaultUnit: 'g' },
  { name: '캐슈넛', emoji: '🥜', category: '가공식품', defaultUnit: 'g' },
  { name: '피스타치오', emoji: '🥜', category: '가공식품', defaultUnit: 'g' },
  { name: '해바라기씨', emoji: '🌻', category: '가공식품', defaultUnit: 'g' },
  { name: '호박씨', emoji: '🎃', category: '가공식품', defaultUnit: 'g' },
  { name: '잣', emoji: '🥜', category: '가공식품', defaultUnit: 'g' },

  // 조미료
  { name: '소금', emoji: '🧂', category: '조미료', defaultUnit: 'g' },
  { name: '굵은소금', emoji: '🧂', category: '조미료', defaultUnit: 'g' },
  { name: '꽃소금', emoji: '🧂', category: '조미료', defaultUnit: 'g' },
  { name: '설탕', emoji: '🧂', category: '조미료', defaultUnit: 'g' },
  { name: '흑설탕', emoji: '🧂', category: '조미료', defaultUnit: 'g' },
  { name: '올리고당', emoji: '🍯', category: '조미료', defaultUnit: 'ml' },
  { name: '꿀', emoji: '🍯', category: '조미료', defaultUnit: 'ml' },
  { name: '물엿', emoji: '🍯', category: '조미료', defaultUnit: 'ml' },
  { name: '조청', emoji: '🍯', category: '조미료', defaultUnit: 'ml' },
  { name: '간장', emoji: '🥫', category: '조미료', defaultUnit: 'ml' },
  { name: '진간장', emoji: '🥫', category: '조미료', defaultUnit: 'ml' },
  { name: '국간장', emoji: '🥫', category: '조미료', defaultUnit: 'ml' },
  { name: '양조간장', emoji: '🥫', category: '조미료', defaultUnit: 'ml' },
  { name: '식초', emoji: '🧴', category: '조미료', defaultUnit: 'ml' },
  { name: '사과식초', emoji: '🧴', category: '조미료', defaultUnit: 'ml' },
  { name: '현미식초', emoji: '🧴', category: '조미료', defaultUnit: 'ml' },
  { name: '고춧가루', emoji: '🌶️', category: '조미료', defaultUnit: 'g' },
  { name: '고운고춧가루', emoji: '🌶️', category: '조미료', defaultUnit: 'g' },
  { name: '굵은고춧가루', emoji: '🌶️', category: '조미료', defaultUnit: 'g' },
  { name: '후추', emoji: '🧂', category: '조미료', defaultUnit: 'g' },
  { name: '통후추', emoji: '🧂', category: '조미료', defaultUnit: 'g' },
  { name: '흰후추', emoji: '🧂', category: '조미료', defaultUnit: 'g' },
  { name: '다진마늘', emoji: '🧄', category: '조미료', defaultUnit: 'g' },
  { name: '마늘가루', emoji: '🧄', category: '조미료', defaultUnit: 'g' },
  { name: '생강가루', emoji: '🫚', category: '조미료', defaultUnit: 'g' },
  { name: '맛술', emoji: '🍶', category: '조미료', defaultUnit: 'ml' },
  { name: '청주', emoji: '🍶', category: '조미료', defaultUnit: 'ml' },
  { name: '미림', emoji: '🍶', category: '조미료', defaultUnit: 'ml' },
  { name: '굴소스', emoji: '🥫', category: '조미료', defaultUnit: 'ml' },
  { name: '피시소스', emoji: '🥫', category: '조미료', defaultUnit: 'ml' },
  { name: '케첩', emoji: '🥫', category: '조미료', defaultUnit: 'ml' },
  { name: '토마토소스', emoji: '🍅', category: '조미료', defaultUnit: 'ml' },
  { name: '토마토페이스트', emoji: '🍅', category: '조미료', defaultUnit: 'g' },
  { name: '마요네즈', emoji: '🥫', category: '조미료', defaultUnit: 'ml' },
  { name: '머스타드', emoji: '🥫', category: '조미료', defaultUnit: 'g' },
  { name: '겨자', emoji: '🥫', category: '조미료', defaultUnit: 'g' },
  { name: '와사비', emoji: '🥫', category: '조미료', defaultUnit: 'g' },
  { name: '카레가루', emoji: '🍛', category: '조미료', defaultUnit: 'g' },
  { name: '카레블럭', emoji: '🍛', category: '조미료', defaultUnit: '개' },
  { name: '춘장', emoji: '🥫', category: '조미료', defaultUnit: 'g' },
  { name: '돈까스소스', emoji: '🥫', category: '조미료', defaultUnit: 'ml' },
  { name: '우스터소스', emoji: '🥫', category: '조미료', defaultUnit: 'ml' },
  { name: '타바스코', emoji: '🌶️', category: '조미료', defaultUnit: 'ml' },
  { name: '칠리소스', emoji: '🌶️', category: '조미료', defaultUnit: 'ml' },
  { name: '스리라차', emoji: '🌶️', category: '조미료', defaultUnit: 'ml' },
  { name: '참깨', emoji: '⚪', category: '조미료', defaultUnit: 'g' },
  { name: '들깨', emoji: '⚪', category: '조미료', defaultUnit: 'g' },
  { name: '들깨가루', emoji: '⚪', category: '조미료', defaultUnit: 'g' },
  { name: '통깨', emoji: '⚪', category: '조미료', defaultUnit: 'g' },
  { name: '깨소금', emoji: '⚪', category: '조미료', defaultUnit: 'g' },
  { name: '바질', emoji: '🌿', category: '조미료', defaultUnit: 'g' },
  { name: '로즈마리', emoji: '🌿', category: '조미료', defaultUnit: 'g' },
  { name: '타임', emoji: '🌿', category: '조미료', defaultUnit: 'g' },
  { name: '오레가노', emoji: '🌿', category: '조미료', defaultUnit: 'g' },
  { name: '파슬리', emoji: '🌿', category: '조미료', defaultUnit: 'g' },
  { name: '고수', emoji: '🌿', category: '조미료', defaultUnit: 'g' },
  { name: '계피', emoji: '🟤', category: '조미료', defaultUnit: 'g' },
  { name: '팔각', emoji: '⭐', category: '조미료', defaultUnit: 'g' },
  { name: '월계수잎', emoji: '🍃', category: '조미료', defaultUnit: '장' },
  { name: '육수팩', emoji: '🥫', category: '조미료', defaultUnit: '개' },
  { name: '다시다', emoji: '🥫', category: '조미료', defaultUnit: 'g' },
  { name: '멸치액젓', emoji: '🥫', category: '조미료', defaultUnit: 'ml' },
  { name: '까나리액젓', emoji: '🥫', category: '조미료', defaultUnit: 'ml' },
  { name: '새우젓', emoji: '🦐', category: '조미료', defaultUnit: 'g' },
  { name: 'MSG', emoji: '🧂', category: '조미료', defaultUnit: 'g' },
];

export function getTemplatesByCategory(category: string): IngredientTemplate[] {
  if (category === '전체') {
    return ingredientTemplates;
  }
  return ingredientTemplates.filter((item) => item.category === category);
}

// 이모지가 없는 재료를 추가할 때 사용할 수 있는 헬퍼 함수
export function addCustomIngredient(
  name: string,
  category: string,
  defaultUnit: string = 'g',
  emoji: string = '🍽️',
): IngredientTemplate {
  return {
    name,
    emoji,
    category,
    defaultUnit,
  };
}

// 카테고리별 대표 이모지 맵
export const categoryDefaultEmojis: Record<string, string> = {
  채소: '🥬',
  과일: '🍎',
  육류: '🥩',
  생선류: '🐟',
  유제품: '🥛',
  가공식품: '🍽️',
  조미료: '🧂',
  기타: '🍴',
};
